/**
 * Reasons for Boson Protocol transactions to revert
 */
exports.RevertReasons = {
  // Access related
  ACCESS_DENIED: "AccessDenied",
  NOT_BUYER_OR_SELLER: "NotBuyerOrSeller",
  NOT_VOUCHER_HOLDER: "NotVoucherHolder",
  CAN_ONLY_REVOKE_SELF: "AccessControl: can only renounce roles for self",

  // Pause related
  NOT_PAUSED: "NotPaused",
  REGION_PAUSED: "RegionPaused",

  // General
  INVALID_ADDRESS: "InvalidAddress",
  INVALID_STATE: "InvalidState",
  ARRAY_LENGTH_MISMATCH: "ArrayLengthMismatch",
  REENTRANCY_GUARD: "ReentrancyGuard",
  NON_ASCENDING_ORDER: "NonAscendingOrder",
  UNEXPECTED_DATA_RETURNED: "UnexpectedDataReturned",

  // Facet initializer related
  ALREADY_INITIALIZED: "AlreadyInitialized",
  PROTOCOL_INITIALIZATION_FAILED: "ProtocolInitializationFailed",
  VERSION_MUST_BE_SET: "VersionMustBeSet",
  ADDRESSES_AND_CALLDATA_LENGTH_MISMATCH: "AddressesAndCalldataLengthMismatch",
  WRONG_CURRENT_VERSION: "WrongCurrentVersion",
  DIRECT_INITIALIZATION_NOT_ALLOWED: "DirectInitializationNotAllowed",
  TWINS_ALREADY_EXIST: "TwinsAlreadyExist",

  // Offer related
  NOT_ASSISTANT: "NotAssistant",
  NO_SUCH_OFFER: "NoSuchOffer",
  INVALID_OFFER: "InvalidOffer",
  OFFER_HAS_BEEN_VOIDED: "OfferHasBeenVoided",
  OFFER_PERIOD_INVALID: "InvalidOfferPeriod",
  OFFER_PENALTY_INVALID: "InvalidOfferPenalty",
  OFFER_MUST_BE_ACTIVE: "OfferMustBeActive",
  OFFER_MUST_BE_UNIQUE: "OfferMustBeUnique",
  CANNOT_COMMIT: "CannotCommit",
  EXCHANGE_FOR_OFFER_EXISTS: "ExchangeForOfferExists",
  AMBIGUOUS_VOUCHER_EXPIRY: "AmbiguousVoucherExpiry",
  REDEMPTION_PERIOD_INVALID: "InvalidRedemptionPeriod",
  INVALID_DISPUTE_PERIOD: "InvalidDisputePeriod",
  INVALID_RESOLUTION_PERIOD: "InvalidResolutionPeriod",
  INVALID_DISPUTE_RESOLVER: "InvalidDisputeResolver",
  INVALID_QUANTITY_AVAILABLE: "InvalidQuantityAvailable",
  DR_UNSUPPORTED_FEE: "DRUnsupportedFee",
  AGENT_FEE_AMOUNT_TOO_HIGH: "AgentFeeAmountTooHigh",
  TOTAL_FEE_EXCEEDS_LIMIT: "TotalFeeExceedsLimit",
  OFFER_NOT_AVAILABLE: "OfferNotAvailable",
  OFFER_HAS_EXPIRED: "OfferHasExpired",
  OFFER_SOLD_OUT: "OfferSoldOut",
  NO_SUCH_COLLECTION: "NoSuchCollection",
  INVALID_ROYALTY_RECIPIENT: "InvalidRoyaltyRecipient",
  INVALID_ROYALTY_PERCENTAGE: "InvalidRoyaltyPercentage",
  INVALID_PRICE_DISCOVERY_PRICE: "InvalidPriceDiscoveryPrice",
  SELLER_PARAMS_NOT_ALLOWED: "SellerParametersNotAllowed",

  // Group related
  NO_SUCH_GROUP: "NoSuchGroup",
  OFFER_NOT_IN_GROUP: "OfferNotInGroup",
  NOTHING_UPDATED: "NothingUpdated",
  INVALID_CONDITION_PARAMETERS: "InvalidConditionParameters",
  MAX_COMMITS_REACHED: "MaxCommitsReached",
  GROUP_HAS_NO_CONDITION: "GroupHasNoCondition",
  GROUP_HAS_CONDITION: "GroupHasCondition",
  TOKEN_ID_NOT_IN_CONDITION_RANGE: "TokenIdNotInConditionRange",
  INVALID_TOKEN_ID: "InvalidTokenId",

  // Account-related
  MUST_BE_ACTIVE: "MustBeActive",
  NO_SUCH_SELLER: "NoSuchSeller",
  NO_SUCH_ENTITY: "NoSuchEntity",
  SELLER_ADDRESS_MUST_BE_UNIQUE: "SellerAddressMustBeUnique",
  BUYER_ADDRESS_MUST_BE_UNIQUE: "BuyerAddressMustBeUnique",
  DISPUTE_RESOLVER_ADDRESS_MUST_BE_UNIQUE: "DisputeResolverAddressMustBeUnique",
  AGENT_ADDRESS_MUST_BE_UNIQUE: "AgentAddressMustBeUnique",
  NOT_ADMIN: "NotAdmin",
  CLERK_DEPRECATED: "ClerkDeprecated",
  NOT_ADMIN_AND_ASSISTANT: "NotAdminAndAssistant",
  NOT_BUYER_WALLET: "NotBuyerWallet",
  NOT_AGENT_WALLET: "NotAgentWallet",
  NO_SUCH_BUYER: "NoSuchBuyer",
  NO_SUCH_AGENT: "NoSuchAgent",
  WALLET_OWNS_VOUCHERS: "WalletOwnsVouchers",
  NOT_DISPUTE_RESOLVER_ASSISTANT: "NotDisputeResolverAssistant",
  NO_SUCH_DISPUTE_RESOLVER: "NoSuchDisputeResolver",
  INVALID_ESCALATION_PERIOD: "InvalidEscalationPeriod",
  INEXISTENT_DISPUTE_RESOLVER_FEES: "InexistentDisputeResolverFees",
  DUPLICATE_DISPUTE_RESOLVER_FEES: "DuplicateDisputeResolverFees",
  DISPUTE_RESOLVER_FEE_NOT_FOUND: "DisputeResolverFeeNotFound",
  INVALID_AUTH_TOKEN_TYPE: "InvalidAuthTokenType",
  ADMIN_OR_AUTH_TOKEN: "AdminOrAuthToken",
  AUTH_TOKEN_MUST_BE_UNIQUE: "AuthTokenMustBeUnique",
  SELLER_ALREADY_APPROVED: "SellerAlreadyApproved",
  SELLER_NOT_APPROVED: "SellerNotApproved",
  INEXISTENT_ALLOWED_SELLERS_LIST: "InexistentAllowedSellersList",
  INVALID_AGENT_FEE_PERCENTAGE: "InvalidAgentFeePercentage",
  NO_PENDING_UPDATE_FOR_ACCOUNT: "NoPendingUpdateForAccount",
  UNAUTHORIZED_CALLER_UPDATE: "UnauthorizedCallerUpdate",
  NO_UPDATE_APPLIED: "NoUpdateApplied",
  CLONE_CREATION_FAILED: "CloneCreationFailed",
  SELLER_SALT_NOT_UNIQUE: "SellerSaltNotUnique",
  RECIPIENT_NOT_UNIQUE: "RecipientNotUnique",
  INVALID_ROYALTY_RECIPIENT_ID: "InvalidRoyaltyRecipientId",
  WRONG_DEFAULT_RECIPIENT: "WrongDefaultRecipient",
  ROYALTY_RECIPIENT_IDS_NOT_SORTED: "RoyaltyRecipientIdsNotSorted",
  CANNOT_REMOVE_DEFAULT_RECIPIENT: "CannotRemoveDefaultRecipient",

  // Twin related
  NO_SUCH_TWIN: "NoSuchTwin",
  NO_TRANSFER_APPROVED: "NoTransferApproved",
  UNSUPPORTED_TOKEN: "UnsupportedToken",
  BUNDLE_FOR_TWIN_EXISTS: "BundleForTwinExists",
  INVALID_SUPPLY_AVAILABLE: "InvalidSupplyAvailable",
  INVALID_AMOUNT: "InvalidAmount",
  INVALID_TWIN_PROPERTY: "InvalidTwinProperty",
  INVALID_TWIN_TOKEN_RANGE: "InvalidTwinTokenRange",
  INVALID_TOKEN_ADDRESS: "InvalidTokenAddress",

  // Bundle related
  NO_SUCH_BUNDLE: "NoSuchBundle",
  TWIN_NOT_IN_BUNDLE: "TwinsNotInBundle",
  OFFER_NOT_IN_BUNDLE: "OfferNotInBundle",
  BUNDLE_OFFER_MUST_BE_UNIQUE: "BundleOfferMustBeUnique",
  BUNDLE_TWIN_MUST_BE_UNIQUE: "BundleTwinMustBeUnique",
  INSUFFICIENT_TWIN_SUPPLY_TO_COVER_BUNDLE_OFFERS: "InsufficientTwinSupplyToCoverBundleOffers",
  BUNDLE_REQUIRES_AT_LEAST_ONE_TWIN_AND_ONE_OFFER: "BundleRequiresAtLeastOneTwinAndOneOffer",

  // Exchange related
  NO_SUCH_EXCHANGE: "NoSuchExchange",
  DISPUTE_PERIOD_NOT_ELAPSED: "DisputePeriodNotElapsed",
  VOUCHER_NOT_REDEEMABLE: "VoucherNotRedeemable",
  VOUCHER_EXTENSION_NOT_VALID: "VoucherExtensionNotValid",
  VOUCHER_STILL_VALID: "VoucherStillValid",
  VOUCHER_HAS_EXPIRED: "VoucherHasExpired",
  EXCHANGE_IS_NOT_IN_A_FINAL_STATE: "ExchangeIsNotInAFinalState",
  INVALID_RANGE_LENGTH: "InvalidRangeLength",
  EXCHANGE_ALREADY_EXISTS: "ExchangeAlreadyExists",
  INVALID_TARGET_EXCHANGE_STATE: "InvalidTargeExchangeState",

  // Voucher related
  EXCHANGE_ID_IN_RESERVED_RANGE: "ExchangeIdInReservedRange",
  NO_RESERVED_RANGE_FOR_OFFER: "NoReservedRangeForOffer",
  OFFER_RANGE_ALREADY_RESERVED: "OfferRangeAlreadyReserved",
  INVALID_RANGE_START: "InvalidRangeStart",
  INVALID_AMOUNT_TO_MINT: "InvalidAmountToMint",
  NO_SILENT_MINT_ALLOWED: "NoSilentMintAllowed",
  OFFER_EXPIRED_OR_VOIDED: "OfferExpiredOrVoided",
  OFFER_STILL_VALID: "OfferStillValid",
  AMOUNT_EXCEEDS_RANGE_OR_NOTHING_TO_BURN: "AmountExceedsRangeOrNothingToBurn",
  INVALID_TO_ADDRESS: "InvalidToAddress",
  EXTERNAL_CALL_FAILED: "ExternalCallFailed",
  INTERACTION_NOT_ALLOWED: "InteractionNotAllowed",

  // Funds related
  NATIVE_WRONG_ADDRESS: "NativeWrongAddress",
  NATIVE_WRONG_AMOUNT: "NativeWrongAmount",
  TOKEN_TRANSFER_FAILED: "TokenTransferFailed",
  INSUFFICIENT_VALUE_RECEIVED: "InsufficientValueReceived",
  INSUFFICIENT_AVAILABLE_FUNDS: "InsufficientAvailableFunds",
  NATIVE_NOT_ALLOWED: "NativeNotAllowed",
  TOKEN_AMOUNT_MISMATCH: "TokenAmountMismatch",
  NOTHING_TO_WITHDRAW: "NothingToWithdraw",
  NOT_AUTHORIZED: "NotAuthorized",
  ZERO_DEPOSIT_NOT_ALLOWED: "ZeroDepositNotAllowed",

  // Outside the protocol revert reasons
  ERC20_EXCEEDS_BALANCE: "ERC20: transfer amount exceeds balance",
  ERC20_INSUFFICIENT_ALLOWANCE: "ERC20: insufficient allowance",
  ERC20_PAUSED: "ERC20Pausable: token transfer while paused",
  EOA_FUNCTION_CALL: "Transaction reverted: function call to a non-contract account",
  EOA_FUNCTION_CALL_SAFE_ERC20: "Address: call to non-contract",
  ERC721_INVALID_TOKEN_ID: "ERC721: invalid token ID",
  ERC721_CALLER_NOT_OWNER_OR_APPROVED: "ERC721: caller is not token owner or approved",
  OWNABLE_NOT_OWNER: "Ownable: caller is not the owner",
  OWNABLE_ZERO_ADDRESS: "Ownable: new owner is the zero address",
  SAFE_ERC20_LOW_LEVEL_CALL: "SafeERC20: low-level call failed",
  SAFE_ERC20_OPERATION_FAILED: "SafeERC20: ERC20 operation did not succeed",
  INITIALIZABLE_ALREADY_INITIALIZED: "Initializable: contract is already initialized",
  ERC721_NON_RECEIVER: "ERC721: transfer to non ERC721Receiver implementer",
  BUYER_CONTRACT_REVERT: "BuyerContract: revert",

  // Meta-Transactions related
  NONCE_USED_ALREADY: "NonceUsedAlready",
  FUNCTION_CALL_NOT_SUCCESSFUL: "Function call not successful",
  INVALID_SIGNATURE: "InvalidSignature",
  SIGNATURE_VALIDATION_FAILED: "SignatureValidationFailed",
  INVALID_FUNCTION_NAME: "InvalidFunctionName",
  FUNCTION_NOT_ALLOWLISTED: "FunctionNotAllowlisted",

  // Dispute related
  DISPUTE_PERIOD_HAS_ELAPSED: "DisputePeriodHasElapsed",
  UNSUPPORTED_MUTUALIZER: "UnsupportedMutualizer",
  DISPUTE_HAS_EXPIRED: "DisputeHasExpired",
  INVALID_BUYER_PERCENT: "InvalidBuyerPercent",
  DISPUTE_STILL_VALID: "DisputeStillValid",
  INVALID_DISPUTE_TIMEOUT: "InvalidDisputeTimeout",
  ESCALATION_NOT_ALLOWED: "EscalationNotAllowed",
  INVALID_TARGET_DISPUTE_STATE: "InvalidTargeDisputeState",

  // Config related
  FEE_PERCENTAGE_INVALID: "InvalidFeePercentage",
  VALUE_ZERO_NOT_ALLOWED: "ValueZeroNotAllowed",
  ARRAY_LENGTH_MISSMATCH: "ArrayLengthMissmatch",

  // ERC2981 related
  ROYALTY_FEE_INVALID: "InvalidRoyaltyFee",

  // Diamond related
  TOO_MANY_FUNCTIONS: "Too many functions on facet.",
  ONLY_UPGRADER: "Caller must have UPGRADER role",
  NO_SELECTORS_TO_CUT: "LibDiamondCut: No selectors in facet to cut",
  FUNCTION_ALREADY_EXISTS: "LibDiamondCut: Can't add function that already exists",
  REMOVING_FUNCTION_DOES_NOT_EXIST: "LibDiamondCut: Can't remove function that doesn't exist",
  REMOVING_NON_ZERO_ADDRESS_FACET: "LibDiamondCut: Remove facet address must be address(0)",
  REMOVING_IMMUTABLE_FUNCTION: "LibDiamondCut: Can't remove immutable function",
  REPLACING_IMMUTABLE_FUNCTION: "LibDiamondCut: Can't replace immutable function",
  REPLACING_WITH_SAME_FUNCTION: "LibDiamondCut: Can't replace function with same function",
  REPLACING_FUNCTION_DOES_NOT_EXIST: "LibDiamondCut: Can't replace function that doesn't exist",
  CONTRACT_NOT_ALLOWED: "Address cannot be a contract",
  INIT_REVERTED: "LibDiamondCut: _init function reverted",
  INIT_ZERO_ADDRESS_NON_EMPTY_CALLDATA: "LibDiamondCut: _init is address(0) but _calldata is not empty",
  INIT_EMPTY_CALLDATA_NON_ZERO_ADDRESS: "LibDiamondCut: _calldata is empty but _init is not address(0)",
  INIT_ADDRESS_WITH_NO_CODE: "LibDiamondCut: _init address has no code",

  // Price discovery related
  PRICE_MISMATCH: "PriceMismatch",
  TOKEN_ID_MISMATCH: "TokenIdMismatch",
  VOUCHER_TRANSFER_NOT_ALLOWED: "VoucherTransferNotAllowed",
  VOUCHER_NOT_RECEIVED: "VoucherNotReceived",
  VOUCHER_NOT_TRANSFERRED: "VoucherNotTransferred",
  UNEXPECTED_ERC721_RECEIVED: "UnexpectedERC721Received",
  FEE_AMOUNT_TOO_HIGH: "FeeAmountTooHigh",
  INVALID_PRICE_DISCOVERY: "InvalidPriceDiscovery",
  INVALID_CONDUIT_ADDRESS: "InvalidConduitAddress",
  TOKEN_ID_MANDATORY: "TokenIdMandatory",
  NEGATIVE_PRICE_NOT_ALLOWED: "NegativePriceNotAllowed",
  PRICE_DOES_NOT_COVER_PENALTY: "PriceDoesNotCoverPenalty",

  //Fee Table related
  FEE_TABLE_ASSET_NOT_SUPOPRTED: "FeeTableAssetNotSupported",

  // DR Fee Mutualizer related
  DEPOSITS_RESTRICTED_TO_OWNER: "DepositsRestrictedToOwner",
  INVALID_RECIPIENT: "InvalidRecipient",
  INSUFFICIENT_POOL_BALANCE: "InsufficientPoolBalance",
  INVALID_SELLER_ID: "InvalidSellerId",
  MAX_AMOUNT_PER_TX_MUST_BE_GREATER_THAN_ZERO: "MaxAmountPerTxMustBeGreaterThanZero",
  MAX_TOTAL_MUST_BE_GREATER_THAN_OR_EQUAL_TO_MAX_PER_TX: "MaxTotalMustBeGreaterThanOrEqualToMaxPerTx",
  TIME_PERIOD_MUST_BE_GREATER_THAN_ZERO: "TimePeriodMustBeGreaterThanZero",
  AGREEMENT_ALREADY_ACTIVE: "AgreementAlreadyActive",
  AGREEMENT_IS_VOIDED: "AgreementIsVoided",
  INVALID_AGREEMENT_ID: "InvalidAgreementId",
  ONLY_PROTOCOL: "OnlyProtocol",
  INVALID_PROTOCOL_ADDRESS: "InvalidProtocolAddress",
  INVALID_EXCHANGE_ID: "InvalidExchangeId",
  AGREEMENT_ALREADY_EXISTS: "AgreementAlreadyExists",
  AGREEMENT_ALREADY_VOIDED: "AgreementAlreadyVoided",
  SELLER_NOT_FOUND: "SellerNotFound",
  SAME_MUTUALIZER_ADDRESS: "SameMutualizerAddress",
};
