#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

find . -name '*.js' -not -path '*/node_modules/*' | xargs git diff --cached --name-only | xargs -r npx eslint --fix
find . -name '*.js' -not -path '*/node_modules/*' | xargs git diff --cached --name-only | xargs -r npx prettier --write
git diff --cached --name-only --diff-filter=d | grep -e ^contracts -e sol$ | xargs -r npx solhint --fix 
git diff --cached --name-only --diff-filter=d | grep -e ^contracts -e sol$ | xargs -r npx prettier --write
npm run natspec-interface-id:fix
