#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

find . -name '*.js' -not -path '*/node_modules/*' | xargs git diff --cached --name-only | xargs npm run tidy:scripts
git diff --cached --name-only | grep contracts/ | xargs npm run tidy:contracts
npm run natspec-interface-id:fix
